name: Deploy to VPS with Docker

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    # ✅ Compilar el backend con Maven
    - name: Build Spring Boot app
      run: |
        cd API/MisFinanzasBack
        mvn clean package -DskipTests

    # ✅ Compilar Angular
    - name: Build Angular app
      run: |
        npm install -g @angular/cli
        cd WEB/MisFinanzasFront
        npm install
        ng build --configuration production

    # ✅ Copiar los archivos compilados a la VPS
    - name: Copiar archivos compilados a VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: |
          API/MisFinanzasBack/target/MisFinanzas-0.0.1-SNAPSHOT.jar
          WEB/MisFinanzasFront/dist/MisFinanzas/
        target: /home/jonathan/proyectos/mi-app

    # ✅ Conectarse a la VPS y reconstruir imágenes
    - name: Desplegar en la VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/jonathan/proyectos/mi-app
          docker compose down
          docker compose up -d --build
